import React from "react"
import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer"
import type { BirthChart } from "./astrology"
import type { NumerologyProfile } from "./numerology"
import {
  getLifePathInterpretation,
  getExpressionInterpretation,
  getSoulUrgeInterpretation,
  getPersonalityInterpretation,
  getBirthdayInterpretation,
} from "./numerology"
import { getSignInterpretation } from "./astrology"

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
  },
  header: {
    marginBottom: 30,
    borderBottom: "2 solid #6366f1",
    paddingBottom: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#6366f1",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: "#64748b",
    marginBottom: 5,
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1e293b",
    marginBottom: 12,
    borderBottom: "1 solid #e2e8f0",
    paddingBottom: 5,
  },
  subsectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#475569",
    marginTop: 10,
    marginBottom: 8,
  },
  row: {
    flexDirection: "row",
    marginBottom: 8,
  },
  label: {
    width: "30%",
    fontSize: 10,
    color: "#64748b",
    fontWeight: "bold",
  },
  value: {
    width: "70%",
    fontSize: 10,
    color: "#1e293b",
  },
  planetRow: {
    flexDirection: "row",
    marginBottom: 6,
    padding: 8,
    backgroundColor: "#f8fafc",
    borderRadius: 4,
  },
  planetName: {
    width: "25%",
    fontSize: 10,
    fontWeight: "bold",
    color: "#1e293b",
  },
  planetSign: {
    width: "25%",
    fontSize: 10,
    color: "#6366f1",
  },
  planetHouse: {
    width: "20%",
    fontSize: 10,
    color: "#64748b",
  },
  planetDegree: {
    width: "30%",
    fontSize: 9,
    color: "#94a3b8",
  },
  interpretation: {
    fontSize: 10,
    lineHeight: 1.6,
    color: "#475569",
    marginTop: 5,
    marginBottom: 10,
  },
  numberCard: {
    backgroundColor: "#f8fafc",
    padding: 12,
    marginBottom: 12,
    borderRadius: 4,
    borderLeft: "3 solid #6366f1",
  },
  numberTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1e293b",
    marginBottom: 4,
  },
  numberValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#6366f1",
    marginBottom: 6,
  },
  aspectRow: {
    flexDirection: "row",
    marginBottom: 5,
    padding: 6,
    backgroundColor: "#f8fafc",
  },
  aspectText: {
    fontSize: 9,
    color: "#475569",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 9,
    color: "#94a3b8",
    borderTop: "1 solid #e2e8f0",
    paddingTop: 10,
  },
  pageNumber: {
    fontSize: 9,
    color: "#94a3b8",
  },
})

interface PDFReportProps {
  userData: {
    fullName: string
    dateOfBirth: string
    birthTime: string
    location: {
      city: string
      country: string
      timezone: string
      lat: number
      lng: number
    }
  }
  birthChart: BirthChart
  numerologyProfile: NumerologyProfile
}

export const PDFReport: React.FC<PDFReportProps> = ({
  userData,
  birthChart,
  numerologyProfile,
}) => {
  const formatDate = (dateStr: string) => {
    try {
      const date = new Date(dateStr)
      return date.toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    } catch {
      return dateStr
    }
  }

  return (
    <Document>
      {/* Page 1: Overview and Birth Data */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Your Cosmic Blueprint</Text>
          <Text style={styles.subtitle}>{userData.fullName}</Text>
          <Text style={styles.subtitle}>Generated by Zynra</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Birth Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Full Name:</Text>
            <Text style={styles.value}>{userData.fullName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date of Birth:</Text>
            <Text style={styles.value}>{formatDate(userData.dateOfBirth)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Birth Time:</Text>
            <Text style={styles.value}>{userData.birthTime}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Birth Location:</Text>
            <Text style={styles.value}>
              {userData.location.city}, {userData.location.country}
            </Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Timezone:</Text>
            <Text style={styles.value}>{userData.location.timezone}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Coordinates:</Text>
            <Text style={styles.value}>
              {userData.location.lat.toFixed(3)}, {userData.location.lng.toFixed(3)}
            </Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>The Big Three</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Sun Sign:</Text>
            <Text style={styles.value}>{birthChart.sun.sign}</Text>
          </View>
          <Text style={styles.interpretation}>
            {getSignInterpretation(birthChart.sun.sign)}
          </Text>

          <View style={styles.row}>
            <Text style={styles.label}>Moon Sign:</Text>
            <Text style={styles.value}>{birthChart.moon.sign}</Text>
          </View>
          <Text style={styles.interpretation}>
            {getSignInterpretation(birthChart.moon.sign)}
          </Text>

          <View style={styles.row}>
            <Text style={styles.label}>Rising Sign:</Text>
            <Text style={styles.value}>{birthChart.ascendant.sign}</Text>
          </View>
          <Text style={styles.interpretation}>
            {getSignInterpretation(birthChart.ascendant.sign)}
          </Text>
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          } />
        </View>
      </Page>

      {/* Page 2: Planetary Positions */}
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Planetary Positions</Text>

          <Text style={styles.subsectionTitle}>Personal Planets</Text>
          <View style={styles.planetRow}>
            <Text style={styles.planetName}>Mercury</Text>
            <Text style={styles.planetSign}>{birthChart.mercury.sign}</Text>
            <Text style={styles.planetHouse}>House {birthChart.mercury.house}</Text>
            <Text style={styles.planetDegree}>{birthChart.mercury.degree.toFixed(2)}°</Text>
          </View>
          <View style={styles.planetRow}>
            <Text style={styles.planetName}>Venus</Text>
            <Text style={styles.planetSign}>{birthChart.venus.sign}</Text>
            <Text style={styles.planetHouse}>House {birthChart.venus.house}</Text>
            <Text style={styles.planetDegree}>{birthChart.venus.degree.toFixed(2)}°</Text>
          </View>
          <View style={styles.planetRow}>
            <Text style={styles.planetName}>Mars</Text>
            <Text style={styles.planetSign}>{birthChart.mars.sign}</Text>
            <Text style={styles.planetHouse}>House {birthChart.mars.house}</Text>
            <Text style={styles.planetDegree}>{birthChart.mars.degree.toFixed(2)}°</Text>
          </View>

          <Text style={styles.subsectionTitle}>Social Planets</Text>
          <View style={styles.planetRow}>
            <Text style={styles.planetName}>Jupiter</Text>
            <Text style={styles.planetSign}>{birthChart.jupiter.sign}</Text>
            <Text style={styles.planetHouse}>House {birthChart.jupiter.house}</Text>
            <Text style={styles.planetDegree}>{birthChart.jupiter.degree.toFixed(2)}°</Text>
          </View>
          <View style={styles.planetRow}>
            <Text style={styles.planetName}>Saturn</Text>
            <Text style={styles.planetSign}>{birthChart.saturn.sign}</Text>
            <Text style={styles.planetHouse}>House {birthChart.saturn.house}</Text>
            <Text style={styles.planetDegree}>{birthChart.saturn.degree.toFixed(2)}°</Text>
          </View>

          <Text style={styles.subsectionTitle}>Outer Planets</Text>
          <View style={styles.planetRow}>
            <Text style={styles.planetName}>Uranus</Text>
            <Text style={styles.planetSign}>{birthChart.uranus.sign}</Text>
            <Text style={styles.planetHouse}>House {birthChart.uranus.house}</Text>
            <Text style={styles.planetDegree}>{birthChart.uranus.degree.toFixed(2)}°</Text>
          </View>
          <View style={styles.planetRow}>
            <Text style={styles.planetName}>Neptune</Text>
            <Text style={styles.planetSign}>{birthChart.neptune.sign}</Text>
            <Text style={styles.planetHouse}>House {birthChart.neptune.house}</Text>
            <Text style={styles.planetDegree}>{birthChart.neptune.degree.toFixed(2)}°</Text>
          </View>
          <View style={styles.planetRow}>
            <Text style={styles.planetName}>Pluto</Text>
            <Text style={styles.planetSign}>{birthChart.pluto.sign}</Text>
            <Text style={styles.planetHouse}>House {birthChart.pluto.house}</Text>
            <Text style={styles.planetDegree}>{birthChart.pluto.degree.toFixed(2)}°</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Major Aspects</Text>
          {birthChart.aspects.slice(0, 10).map((aspect, index) => (
            <View key={index} style={styles.aspectRow}>
              <Text style={styles.aspectText}>
                {aspect.planet1} {aspect.type} {aspect.planet2} (Orb: {aspect.orb.toFixed(2)}°)
              </Text>
            </View>
          ))}
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          } />
        </View>
      </Page>

      {/* Page 3: Numerology */}
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Numerology Profile</Text>

          <View style={styles.numberCard}>
            <Text style={styles.numberTitle}>Life Path Number</Text>
            <Text style={styles.numberValue}>{numerologyProfile.lifePathNumber}</Text>
            <Text style={styles.interpretation}>
              {getLifePathInterpretation(numerologyProfile.lifePathNumber)}
            </Text>
          </View>

          <View style={styles.numberCard}>
            <Text style={styles.numberTitle}>Expression Number</Text>
            <Text style={styles.numberValue}>{numerologyProfile.expressionNumber}</Text>
            <Text style={styles.interpretation}>
              {getExpressionInterpretation(numerologyProfile.expressionNumber)}
            </Text>
          </View>

          <View style={styles.numberCard}>
            <Text style={styles.numberTitle}>Soul Urge Number</Text>
            <Text style={styles.numberValue}>{numerologyProfile.soulUrgeNumber}</Text>
            <Text style={styles.interpretation}>
              {getSoulUrgeInterpretation(numerologyProfile.soulUrgeNumber)}
            </Text>
          </View>

          <View style={styles.numberCard}>
            <Text style={styles.numberTitle}>Personality Number</Text>
            <Text style={styles.numberValue}>{numerologyProfile.personalityNumber}</Text>
            <Text style={styles.interpretation}>
              {getPersonalityInterpretation(numerologyProfile.personalityNumber)}
            </Text>
          </View>

          <View style={styles.numberCard}>
            <Text style={styles.numberTitle}>Birthday Number</Text>
            <Text style={styles.numberValue}>{numerologyProfile.birthdayNumber}</Text>
            <Text style={styles.interpretation}>
              {getBirthdayInterpretation(numerologyProfile.birthdayNumber)}
            </Text>
          </View>
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          } />
          <Text>Generated by Zynra - Your Personal Astrology & Numerology Platform</Text>
        </View>
      </Page>
    </Document>
  )
}
